### ISSUE TITLE
Prepare for version 5

### ISSUE THREAD

**Issue by entorenee** [dslemay/eslint-config-dslemay#167]
There are a number of the dependent plugins which have new rules that have been added which will require a major version bump. The following are outlines for preparing for version 5 of the configuration.

- [ ] Update TypeScript ESlint monorepo to version 3 #162
- [ ] Update Jest plugin to version 23.13.2 #155 
- [ ] Update React plugin to version 7.18.0 #105 
- [ ] Update to ESLint version 7 #156 
- [ ] Validate if ESLint v6 will still be supported with the new rule definitions. I suspect that this version of the configuration will not be compatible with ESLint v6 due to additional ESLint core rules that will be set (and not exist in previous versions)
